title: The Numerical Schemer
author: Christian Himpe
email: 
description: > # this means to ignore newlines until "baseurl:"
  Numerics with Scheme
theme: minima
skin: dark

# social links
twitter_username: modelreduction # DO NOT include the @ character, or else the build will fail!
github_username:  gramian # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
