title: The Numerical Schemer
author: Chrsitian Himpe
email: 
description: > # this means to ignore newlines until "baseurl:"
  Numericas with Scheme
theme: minima

# social links
twitter_username: modelreduction # DO NOT include the @ character, or else the build will fail!
github_username:  gramian # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
